language: java
notifications:
  email: false
  slack:
    secure: ZsAe7L/4a+9ToqepTJn85G3c3stDL5uzSjDgNfaoA8agz+HzAL3XGY4kA7/nX5YeCX47wGEEK6mgHN38zeMIraNp+h81eRh20WEHulU7P8vbwiYSMoZscdT9zcrJ04GB3CJ9wsZG9bC0HYel9sq35HfOLa1hCgVWId8as9NEDId7n3EqAnuWyioGs4jMFK0mpyfadAi9LaW2Tk0P/jbODgreUDluYGSdx8FqVXwg+XEjvTwZ1P4Y4RUvojIub9MXwTsyhL6fuTiz15b3Wo6QesrY8xd0+NyZqN6oaEIblxkdFo3K8QJEpNg+wu5QL/urot8RNFiL0zUjBOrPgs2/snWfZSvRIITRPYYLvrXvtNBW8viToi2bJBP74P4W66/hJINEonPHX1QwqTnP6iefhboAzLX0rF5h2OeAXC0nN2Thw1WVgSZVvDUeHla1yBigemHvuTNyvrJtKnMsqti7AAYCJ3gsX/Djoli+0srDI3lCcXss3yuwGARKNSHjZiSUz/XQRtko76hOEv0omigMmJYEKy5F/yMJsnyW392dHVlxwG6IjRjPysiEmM7O6AHFEwYwY40YpPZNXoWny/Bij+Zuhfl2ypOBYUGHtyqQh8eSsNBBaeQKB8FRGmhQSOuvwEjo9oPojwfyMwsBG1msI6QVbaTOQVRcC4pna+O7WdA=
jdk:
- oraclejdk8
install: echo 'Run Maven Tests'
script: mvn clean install --settings .travis/settings.xml -Dmaven.javadoc.skip=true
  -B -V
after_success: mvn deploy --settings .travis/settings.xml -DskipTests -B -V
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:
  - secure: 3xgLfQ5UuahmxHQB9pktAIrg+6zpf6ugnZ1XUsxxO1IUDcv2slpYKFikawGU9QsEbzZfV0VEpvYdpHGu1BK/I7RYpJo/usdaj0uE9ZVVW5XX+QPuudrSOB2RLU/kCfv1vuw0y/739rtxu41o3sEcTsE7ofLBEFiQOSkyED0aJdEWq83MsTgsbChq9fn6zJuZVAENvqdv4krdzvu/c5wVJaiJw/GiSi/oNapBlVkD+OmLTGG04TjENZtj3WQwh83htnWmye/3KBQYwhwVlfCtSwjFw0JaJzuwBqwC3Dqfo7jqcY+iUDX7LGj5ebfdjz74xT4H1KP2NuxmNzSmF45oCMTUR4qRZljsLRG7UGAQCRpDRZqGCY2diZeYvqLtvVygZ7DofPeIEN1O3863AzJGxhPMgS2r0EmF3C0QhxLqa7uPjCIHe6D+xapbrk8eSPx3/cM8P1yYMjDKsWbucH1QeiiZx8oU6xOiWf1vWyLQ9ACbPw2p+/V3bZBCJo/d/3LnKq9xx3yWxqflZvYnv2a4QNcGlYLsQqv+oR6Q28sHLMI/sLKZyPmDFbrhpVTvSR7jWDlUNLhXWgL5C5lOJShYl2uj1H97alVPqgjYcLxzJCbD6er5wxN4eP9lVFvO9WKGNaw7NZz5R/uU67Gk1LaeTHlu14xCOCVbsRFCIxexNGk=
  - secure: LPwx/L0Z/3Q7wJBKX0SYiMJvPUHneBTMmkwg00HXYJdoRDgyv4TiOAecV2VKOZQjVoSokJv6BU/+gDHx/Yl3s5AuSdMFF+BaWYIc9nv+cHOxcWZ9bEAz0XSDc5xKp4I3lbJJdweFO/hMzApPgktNFSAYghl5xqzhkUeOdnzP+hMvRr6LSTbIP1jArfgf2p9EW9+narTuzsI/IoL6uox8XTDjdAK2Sm5ANgKetcQ+pJ91Fs1TLs5FTQhGBZIBVy+0XfJ38931MvF2hC0KB2XE+Gm1xHpORF1Q94W49wIQGbNsOutTgvwiFEpoXb+Spd2M8W03ptMHi7VyN4+7oIC/ZIyv8B27IchTddNN/NHp1470haYBbBoHXF6JOJfIMoH2agXoVJDQdTwg3lUhPDnjjxRcDznjMw+A0WMM+GyS0q/vfmOMiH0be0Ugor3pZgTDPlZppdXhyZ2Q88rXbYaFU21OqwPOoAwWO697I4RBMcr0YwxTtl/owCQEuJImMDAUKLM+KnbqtUv/n64hj5xpZV2lsEj1d7S3lRUtL8UNlYW++FUFRm1uoT+TDsG1D+kFZQvKT02GnOofH2MrTugYdgPJs9skFbZxyVX/FWfdEo6XAHHFcMJhpKsEfOik4QhLsDD/sOq/hv+MIDmgd4YTo9VYtbXZlg/xcXgq+/rsCOA=
